# Generated by Django 5.2.2 on 2025-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profiles/default/avatar.png', upload_to='users/profile_pics/'),
        ),
    ]
